#highlighter: none
#markdown: kramdown
#kramdown:
#  syntax_highlighter_opts:
#    disable : true

sass:
  sass_dir: _sass
  style: compressed
#defaults:
#  - scope:
#      path: "assets/img"
#    values:
#      image: true